/det/select Prototype

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/gen/select pythia
/gen/pythia/read_file studies/test_stand/w_to_muon.cmnd
/gen/pythia/process hard

/gen/pythia/cuts/clear
/gen/pythia/cuts/add 13 | | -0.15:0.15 | -0.1:0.1 rad
/gen/pythia/cuts/add 14 | | -0.15:0.15 | -0.1:0.1 rad

/run/beamOn 100000
