/det/select Prototype

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/gen/select range

/gen/range/id 13
/gen/range/vertex 0 0 81.28 m

#/gen/range/p_unit 0 0 1
#/gen/range/p_mag {pmag} GeV/c
/gen/range/pT_min {pmag} GeV/c
/gen/range/pT_max {pmag} GeV/c

/gen/range/eta_min -0.04882
/gen/range/eta_max -0.0121
/gen/range/phi_min 1.553 rad
/gen/range/phi_max 1.589 rad

/run/beamOn {count}

# --------- OLD RUNS --------- #
# ROUND 1
# /gen/range/phi_min -0.05 rad
# /gen/range/phi_max  0.05 rad
# /gen/range/eta_min -0.05
# /gen/range/eta_max  0.05
