/det/select Prototype

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/gen/select range

/gen/range/id 13
/gen/range/vertex 0 0 81
/gen/range/p_unit 0 0 -1

/gen/range/phi_min -0.065 rad
/gen/range/phi_max  0.065 rad
/gen/range/eta_min -0.4
/gen/range/eta_max  0.9

/gen/range/p_mag {pmag} GeV/c

/run/beamOn {count}

# --------- OLD RUNS --------- #
# ROUND 1
# /gen/range/phi_min -0.05 rad
# /gen/range/phi_max  0.05 rad
# /gen/range/eta_min -0.05
# /gen/range/eta_max  0.05
