/vis/open OGL 700x700-0+0

# /vis/open OIX
# /vis/open DAWNFILE
# /vis/open HepRepFile
# /vis/open VRML2FILE

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 90. 180.
/vis/viewer/zoom 1.4

# /vis/viewer/set/style wireframe
# /vis/viewer/set/auxiliaryEdge true
# /vis/viewer/set/lineSegmentsPerCircle 100

/vis/scene/add/axes 0 0 0 1 m

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/add/hits

#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add mu-

# /vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
# /vis/modeling/trajectories/list
# /vis/modeling/trajectories/drawByParticleID-0/set e+ yellow

/vis/scene/endOfEventAction accumulate

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/vis/viewer/flush