/vis/open OGL 700x700-0+0

# /vis/open OIX
# /vis/open DAWNFILE
# /vis/open HepRepFile
# /vis/open VRML2FILE

/vis/viewer/set/autoRefresh false

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi  90. 180.
/vis/viewer/set/lightsThetaPhi    180.   0.
/vis/viewer/zoom 1.4

/vis/scene/add/axes 0 0 0 50 cm

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/add/hits

/vis/scene/endOfEventAction accumulate

/vis/viewer/set/autoRefresh true
/vis/viewer/flush